baseURL = 'https://elisarit.github.io/remission-path/'
languageCode = 'ru-ru'
title = 'Путь ремиссии'
theme = 'relearn'

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
  name = "Обратная связь"
  url = "/contact/feedback/"
  weight = 30
